name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: format
      run: make python_format

    - name: lint
      run: make python_lint

    - name: Run Tests with Unittest
      run: python -m unittest discover -s tests -p 'test_*.py'

    - name: Run Python Benchmarks
      run: python3 benchmark_and_plot.py
